name: Build and Deploy to Dockerhub

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jestico/ci-cd-app:latest

      - name: Verify Pushed Image
        run: docker pull jestico/ci-cd-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        script: |
          sudo docker pull jestico/ci-cd-app:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name web-app -p 3005:3000 jestico/ci-cd-app:latest